import { ADUser } from '@types'

export const mockUsers: ADUser[] = [
  {
    id: '1',
    displayName: 'Ahmet Yılmaz',
    employeeId: 'SİC-00001',
    title: 'Senior Developer',
    department: 'Engineering',
    organization: 'Tech Division',
    email: 'ahmet.yilmaz@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '2',
    displayName: 'Fatma Özdemir',
    employeeId: 'SİC-00002',
    title: 'Product Manager',
    department: 'Product',
    organization: 'Product Division',
    email: 'fatma.ozdemir@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '3',
    displayName: 'Zeynep Kaya',
    employeeId: 'SİC-00003',
    title: 'UX Designer',
    department: 'Design',
    organization: 'Product Division',
    email: 'zeynep.kaya@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '4',
    displayName: 'Mehmet Ali İşler',
    employeeId: 'SİC-00004',
    title: 'Backend Developer',
    department: 'Engineering',
    organization: 'Tech Division',
    email: 'mehmet.ali@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '5',
    displayName: 'Ayşe Deniz',
    employeeId: 'SİC-00005',
    title: 'Frontend Developer',
    department: 'Engineering',
    organization: 'Tech Division',
    email: 'ayse.deniz@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '6',
    displayName: 'Selim Karadöner',
    employeeId: 'SİC-00006',
    title: 'DevOps Engineer',
    department: 'Infrastructure',
    organization: 'Tech Division',
    email: 'selim.karadoner@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '7',
    displayName: 'Burcu Şahin',
    employeeId: 'SİC-00007',
    title: 'HR Manager',
    department: 'Human Resources',
    organization: 'Operations',
    email: 'burcu.sahin@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '8',
    displayName: 'İbrahim Göl',
    employeeId: 'SİC-00008',
    title: 'Finance Manager',
    department: 'Finance',
    organization: 'Operations',
    email: 'ibrahim.gol@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '9',
    displayName: 'Sinem Özkan',
    employeeId: 'SİC-00009',
    title: 'Marketing Specialist',
    department: 'Marketing',
    organization: 'Business',
    email: 'sinem.ozkan@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '10',
    displayName: 'Haktan Barlı',
    employeeId: 'SİC-00010',
    title: 'Sales Manager',
    department: 'Sales',
    organization: 'Business',
    email: 'haktan.barli@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '11',
    displayName: 'Elif Kırtıl',
    employeeId: 'SİC-00011',
    title: 'QA Engineer',
    department: 'Quality Assurance',
    organization: 'Tech Division',
    email: 'elif.kirtil@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '12',
    displayName: 'Murat Koçak',
    employeeId: 'SİC-00012',
    title: 'Senior Designer',
    department: 'Design',
    organization: 'Product Division',
    email: 'murat.kocak@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '13',
    displayName: 'Leila Emiroğlu',
    employeeId: 'SİC-00013',
    title: 'Data Analyst',
    department: 'Analytics',
    organization: 'Business',
    email: 'leila.emiroglu@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '14',
    displayName: 'Deniz Akbaş',
    employeeId: 'SİC-00014',
    title: 'Security Engineer',
    department: 'Infrastructure',
    organization: 'Tech Division',
    email: 'deniz.akbas@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
  {
    id: '15',
    displayName: 'Gökçe Sonar',
    employeeId: 'SİC-00015',
    title: 'Content Manager',
    department: 'Marketing',
    organization: 'Business',
    email: 'gokce.sonar@company.com',
    thumbnailPhotoUrl: null,
    hasPhoto: false,
  },
]

export const mockDepartments = Array.from(
  new Set(mockUsers.map((u) => u.department))
).sort()

export const mockOrganizations = Array.from(
  new Set(mockUsers.map((u) => u.organization))
).sort()
